FROM ubuntu:20.04

ENV GODOT_ENGINE_URL=https://downloads.tuxfamily.org/godotengine/3.2/mono/Godot_v3.2-stable_mono_linux_server_64.zip
ENV GODOT_EXPORTS_URL=https://downloads.tuxfamily.org/godotengine/3.2/mono/Godot_v3.2-stable_mono_export_templates.tpz